# Generated by Django 6.0.3 on 2026-04-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_admin_id_alter_cgpa_id_alter_fees_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
